-- 插入题目数据
INSERT INTO questions (id, text_zh, text_en, dimension) VALUES
(1, '我有很多想象力。', 'I have a vivid imagination.', 'openness'),
(6, '我喜欢尝试新事物。', 'I like to try new things.', 'openness'),
(11, '我对艺术和美学有浓厚兴趣。', 'I have a strong interest in art and aesthetics.', 'openness'),
(16, '我喜欢思考抽象的概念。', 'I enjoy thinking about abstract concepts.', 'openness'),
(21, '我经常有创造性的想法。', 'I often have creative ideas.', 'openness'),
(26, '我喜欢探索不同的文化。', 'I like to explore different cultures.', 'openness'),
(31, '我对哲学问题感兴趣。', 'I am interested in philosophical questions.', 'openness'),
(36, '我喜欢学习新技能。', 'I enjoy learning new skills.', 'openness'),
(41, '我对未知事物充满好奇。', 'I am curious about unknown things.', 'openness'),
(46, '我喜欢挑战传统观念。', 'I like to challenge traditional ideas.', 'openness'),
(2, '我总是准时完成任务。', 'I always complete tasks on time.', 'conscientiousness'),
(7, '我做事有条理。', 'I do things in an organized manner.', 'conscientiousness'),
(12, '我注重细节。', 'I pay attention to details.', 'conscientiousness'),
(17, '我坚持完成自己开始的工作。', 'I persist in completing work I start.', 'conscientiousness'),
(22, '我制定计划并按计划执行。', 'I make plans and follow through with them.', 'conscientiousness'),
(27, '我很少拖延。', 'I rarely procrastinate.', 'conscientiousness'),
(32, '我总是做好充分准备。', 'I always prepare thoroughly.', 'conscientiousness'),
(37, '我追求完美。', 'I pursue perfection.', 'conscientiousness'),
(42, '我能够自我约束。', 'I am able to exercise self-control.', 'conscientiousness'),
(47, '我有很强的目标导向。', 'I have strong goal orientation.', 'conscientiousness'),
(3, '我在社交场合中感到自在。', 'I feel comfortable in social situations.', 'extraversion'),
(8, '我喜欢成为关注的焦点。', 'I enjoy being the center of attention.', 'extraversion'),
(13, '我有很多朋友。', 'I have many friends.', 'extraversion'),
(18, '我喜欢参加聚会和活动。', 'I enjoy attending parties and events.', 'extraversion'),
(23, '我很容易与陌生人交谈。', 'I find it easy to talk to strangers.', 'extraversion'),
(28, '我在团队中表现活跃。', 'I am active in team settings.', 'extraversion'),
(33, '我喜欢表达自己的观点。', 'I enjoy expressing my opinions.', 'extraversion'),
(38, '我充满活力。', 'I am full of energy.', 'extraversion'),
(43, '我喜欢热闹的环境。', 'I enjoy lively environments.', 'extraversion'),
(48, '我善于激励他人。', 'I am good at motivating others.', 'extraversion'),
(4, '我信任别人。', 'I trust others.', 'agreeableness'),
(9, '我愿意帮助他人。', 'I am willing to help others.', 'agreeableness'),
(14, '我容易与人相处。', 'I am easy to get along with.', 'agreeableness'),
(19, '我很少与人发生争执。', 'I rarely argue with others.', 'agreeableness'),
(24, '我对人宽容。', 'I am tolerant of others.', 'agreeableness'),
(29, '我体谅他人的感受。', 'I consider others'' feelings.', 'agreeableness'),
(34, '我愿意与他人合作。', 'I am willing to cooperate with others.', 'agreeableness'),
(39, '我关心他人的福祉。', 'I care about others'' well-being.', 'agreeableness'),
(44, '我容易相信他人。', 'I find it easy to trust others.', 'agreeableness'),
(49, '我尽量避免冲突。', 'I try to avoid conflicts.', 'agreeableness'),
(5, '我经常感到焦虑。', 'I often feel anxious.', 'neuroticism'),
(10, '我容易感到沮丧。', 'I am easily discouraged.', 'neuroticism'),
(15, '我经常感到紧张。', 'I often feel tense.', 'neuroticism'),
(20, '我担心很多事情。', 'I worry about many things.', 'neuroticism'),
(25, '我情绪波动较大。', 'My emotions fluctuate greatly.', 'neuroticism'),
(30, '我容易感到压力。', 'I am easily stressed.', 'neuroticism'),
(35, '我经常感到不安。', 'I often feel uneasy.', 'neuroticism'),
(40, '我对批评敏感。', 'I am sensitive to criticism.', 'neuroticism'),
(45, '我容易感到愤怒。', 'I get angry easily.', 'neuroticism'),
(50, '我经常感到孤独。', 'I often feel lonely.', 'neuroticism');

-- 插入 MBTI 类型详细信息
INSERT INTO mbti_types_info (type_code, name_zh, name_en, description_zh, description_en, strengths_zh, strengths_en, challenges_zh, challenges_en) VALUES
('INTJ-A', '建筑师', 'Architect', '富有想像力和战略性思想，冷静自信且具有批判性', 'Imaginative and strategic thinkers, with a plan for everything.', '["独立思考","战略性规划","逻辑分析"]', '["Independent thinking","Strategic planning","Logical analysis"]', '["过度批判","忽视情感因素"]', '["Overly critical","Ignoring emotional factors"]'),
('INTJ-T', '建筑师', 'Architect', '富有想像力和战略性思想，具有强烈的完美主义倾向', 'Imaginative and strategic thinkers, with strong perfectionist tendencies.', '["深度思考","追求卓越","独立性强"]', '["Deep thinking","Pursuing excellence","Strong independence"]', '["过度焦虑","难以表达情感"]', '["Excessive anxiety","Difficulty expressing emotions"]'),
('INTP-A', '逻辑学家', 'Logician', '具有创造力的思想家，喜欢独立思考和探索概念', 'Innovative inventors with an unquenchable thirst for knowledge.', '["分析能力强","好奇心强","独立思考"]', '["Strong analytical ability","Strong curiosity","Independent thinking"]', '["缺乏执行力","忽视实际应用"]', '["Lack of execution","Ignoring practical applications"]'),
('INTP-T', '逻辑学家', 'Logician', '具有创造力的思想家，对知识和理解有强烈的渴望', 'Innovative inventors with strong desire for knowledge and understanding.', '["深度思考","创新思维","逻辑分析"]', '["Deep thinking","Innovative thinking","Logical analysis"]', '["过度分析","社交回避"]', '["Over-analysis","Social avoidance"]'),
('ENTJ-A', '指挥官', 'Commander', '天生的领导者，具有强大的组织和决策能力', 'Bold, imaginative and strong-willed leaders.', '["领导力强","决策果断","目标导向"]', '["Strong leadership","Decisive","Goal-oriented"]', '["缺乏耐心","忽视他人感受"]', '["Lack of patience","Ignoring others'' feelings"]'),
('ENTJ-T', '指挥官', 'Commander', '天生的领导者，但对失败和批评较为敏感', 'Bold, imaginative leaders, but sensitive to failure and criticism.', '["战略思维","执行力强","自信果断"]', '["Strategic thinking","Strong execution","Confident and decisive"]', '["过度批判","难以放松"]', '["Overly critical","Difficulty relaxing"]'),
('ENTP-A', '辩论家', 'Debater', '聪明好奇，喜欢挑战和新想法，充满创新精神', 'Smart and curious thinkers who cannot resist an intellectual challenge.', '["创新思维","沟通能力强","适应性强"]', '["Innovative thinking","Strong communication","Highly adaptable"]', '["缺乏专注","忽视细节"]', '["Lack of focus","Ignoring details"]'),
('ENTP-T', '辩论家', 'Debater', '聪明好奇，但容易质疑自己和周围的世界', 'Smart and curious thinkers, but prone to self-doubt.', '["创造力强","思维敏捷","善于辩论"]', '["Strong creativity","Quick thinking","Good at debating"]', '["过度思考","难以坚持"]', '["Overthinking","Difficulty persisting"]'),
('INFJ-A', '倡导者', 'Advocate', '理想主义且有洞察力，既有爱心又有决心', 'Creative and insightful, inspired and independent.', '["洞察力强","有同理心","坚持价值观"]', '["Strong insight","Empathetic","Values-driven"]', '["过度敏感","完美主义"]', '["Overly sensitive","Perfectionist"]'),
('INFJ-T', '倡导者', 'Advocate', '理想主义且有洞察力，但容易受到压力和批评的影响', 'Creative and insightful, but sensitive to stress and criticism.', '["深度洞察","富有同情心","有创造力"]', '["Deep insight","Compassionate","Creative"]', '["过度焦虑","难以表达需求"]', '["Excessive anxiety","Difficulty expressing needs"]'),
('INFP-A', '调停者', 'Mediator', '理想主义且有同情心，追求个人成长和意义', 'Quiet, open-minded, imaginative, and caring.', '["有创造力","有同理心","忠诚"]', '["Creative","Empathetic","Loyal"]', '["不切实际","难以做出决定"]', '["Unrealistic","Difficulty making decisions"]'),
('INFP-T', '调停者', 'Mediator', '理想主义且有同情心，但容易自我怀疑和情绪波动', 'Quiet, open-minded, but prone to self-doubt and mood swings.', '["富有同情心","创造力强","忠诚"]', '["Compassionate","Creative","Loyal"]', '["过度敏感","逃避冲突"]', '["Overly sensitive","Conflict avoidance"]'),
('ENFJ-A', '主人公', 'Protagonist', '热情且有魅力，关心他人且具有领导力', 'Charismatic and inspiring leaders, able to mesmerize listeners.', '["领导力强","有同理心","沟通能力强"]', '["Strong leadership","Empathetic","Excellent communication"]', '["过度关注他人","忽视自己需求"]', '["Over-focus on others","Neglecting own needs"]'),
('ENFJ-T', '主人公', 'Protagonist', '热情且有魅力，但容易受到他人情绪和批评的影响', 'Charismatic and inspiring, but sensitive to others'' emotions and criticism.', '["激励他人","有同理心","善于沟通"]', '["Inspiring others","Empathetic","Good communicator"]', '["过度敏感","难以拒绝"]', '["Overly sensitive","Difficulty saying no"]'),
('ENFP-A', '竞选者', 'Campaigner', '热情且有创造力，善于交际且充满活力', 'Enthusiastic, creative and sociable free spirits.', '["创造力强","善于交际","适应性强"]', '["Creative","Sociable","Adaptable"]', '["缺乏专注","难以坚持"]', '["Lack of focus","Difficulty following through"]'),
('ENFP-T', '竞选者', 'Campaigner', '热情且有创造力，但容易自我怀疑和情绪波动', 'Enthusiastic and creative, but prone to self-doubt and emotional fluctuations.', '["富有想象力","善于交际","灵活"]', '["Imaginative","Sociable","Flexible"]', '["过度焦虑","难以完成任务"]', '["Excessive anxiety","Difficulty completing tasks"]'),
('ISTJ-A', '物流师', 'Logistician', '实际可靠，注重事实且有责任心', 'Practical and fact-minded, reliable and responsible.', '["有责任心","注重细节","可靠"]', '["Responsible","Detail-oriented","Reliable"]', '["过于僵化","难以适应变化"]', '["Too rigid","Difficulty adapting to change"]'),
('ISTJ-T', '物流师', 'Logistician', '实际可靠，但容易担心和自我怀疑', 'Practical and reliable, but prone to worry and self-doubt.', '["有组织性","负责任","注重细节"]', '["Organized","Responsible","Detail-oriented"]', '["过度焦虑","难以放松"]', '["Excessive anxiety","Difficulty relaxing"]'),
('ISFJ-A', '守护者', 'Defender', '温暖且有责任心，关心他人且有奉献精神', 'Very dedicated and warm protectors, always ready to defend loved ones.', '["有同理心","负责任","忠诚"]', '["Empathetic","Responsible","Loyal"]', '["过度牺牲","难以表达需求"]', '["Self-sacrifice","Difficulty expressing needs"]'),
('ISFJ-T', '守护者', 'Defender', '温暖且有责任心，但容易担心和自我怀疑', 'Very dedicated and warm, but prone to worry and self-doubt.', '["有同理心","负责任","细致"]', '["Empathetic","Responsible","Thorough"]', '["过度焦虑","难以拒绝"]', '["Excessive anxiety","Difficulty saying no"]'),
('ESTJ-A', '执行官', 'Executive', '实际且有责任心，喜欢组织和管理', 'Excellent administrators, unsurpassed at managing things or people.', '["领导力强","有组织性","果断"]', '["Strong leadership","Organized","Decisive"]', '["过于控制","忽视情感因素"]', '["Too controlling","Ignoring emotional factors"]'),
('ESTJ-T', '执行官', 'Executive', '实际且有责任心，但容易担心和自我怀疑', 'Excellent administrators, but prone to worry and self-doubt.', '["组织能力强","负责任","果断"]', '["Strong organizational skills","Responsible","Decisive"]', '["过度焦虑","难以放松"]', '["Excessive anxiety","Difficulty relaxing"]'),
('ESFJ-A', '执政官', 'Consul', '热心且有责任心，关心他人且善于合作', 'Extraordinarily caring, social and popular people, always eager to help.', '["有同理心","善于合作","负责任"]', '["Empathetic","Cooperative","Responsible"]', '["过度迎合","忽视自己需求"]', '["People-pleasing","Neglecting own needs"]'),
('ESFJ-T', '执政官', 'Consul', '热心且有责任心，但容易担心和自我怀疑', 'Extraordinarily caring and social, but prone to worry and self-doubt.', '["有同理心","善于合作","负责任"]', '["Empathetic","Cooperative","Responsible"]', '["过度焦虑","难以拒绝"]', '["Excessive anxiety","Difficulty saying no"]'),
('ISTP-A', '鉴赏家', 'Virtuoso', '灵活且实用，喜欢动手操作和解决问题', 'Bold and practical experimenters, masters of all kinds of tools.', '["实践能力强","适应性强","独立"]', '["Practical skills","Adaptable","Independent"]', '["缺乏计划性","难以表达情感"]', '["Lack of planning","Difficulty expressing emotions"]'),
('ISTP-T', '鉴赏家', 'Virtuoso', '灵活且实用，但容易焦虑和自我怀疑', 'Bold and practical, but prone to anxiety and self-doubt.', '["实践能力强","适应性强","独立"]', '["Practical skills","Adaptable","Independent"]', '["过度焦虑","难以坚持"]', '["Excessive anxiety","Difficulty persisting"]'),
('ISFP-A', '探险家', 'Adventurer', '温和且有艺术性，喜欢享受当下和表达自我', 'Flexible and charming artists, always ready to explore new possibilities.', '["有创造力","有同理心","适应性强"]', '["Creative","Empathetic","Adaptable"]', '["缺乏自信","难以规划未来"]', '["Lack of confidence","Difficulty planning ahead"]'),
('ISFP-T', '探险家', 'Adventurer', '温和且有艺术性，但容易焦虑和自我怀疑', 'Flexible and charming, but prone to anxiety and self-doubt.', '["有创造力","有同理心","敏感"]', '["Creative","Empathetic","Sensitive"]', '["过度敏感","难以拒绝"]', '["Overly sensitive","Difficulty saying no"]'),
('ESTP-A', '企业家', 'Entrepreneur', '精力充沛且现实，喜欢行动和冒险', 'Smart, energetic and very perceptive people, truly enjoy living on the edge.', '["行动力强","适应性强","善于交际"]', '["Action-oriented","Adaptable","Sociable"]', '["缺乏计划性","忽视后果"]', '["Lack of planning","Ignoring consequences"]'),
('ESTP-T', '企业家', 'Entrepreneur', '精力充沛且现实，但容易焦虑和冲动', 'Smart and energetic, but prone to anxiety and impulsiveness.', '["行动力强","适应性强","现实"]', '["Action-oriented","Adaptable","Realistic"]', '["过度焦虑","难以坚持"]', '["Excessive anxiety","Difficulty persisting"]'),
('ESFP-A', '表演者', 'Entertainer', '热情且有魅力，喜欢享受当下和与人交往', 'Spontaneous, energetic and enthusiastic people – life is never boring.', '["善于交际","有创造力","适应性强"]', '["Sociable","Creative","Adaptable"]', '["缺乏计划性","难以独处"]', '["Lack of planning","Difficulty being alone"]'),
('ESFP-T', '表演者', 'Entertainer', '热情且有魅力，但容易焦虑和情绪波动', 'Spontaneous and enthusiastic, but prone to anxiety and emotional fluctuations.', '["善于交际","有创造力","热情"]', '["Sociable","Creative","Enthusiastic"]', '["过度敏感","难以坚持"]', '["Overly sensitive","Difficulty persisting"]');

-- 插入贝尔宾角色数据
INSERT INTO belbin_roles (role_key, name_zh, name_en, description_zh, description_en, characteristics_zh, characteristics_en, contribution_zh, contribution_en, allowable_weaknesses_zh, allowable_weaknesses_en) VALUES
('Plant', '智多星', 'Plant', '富有想象力和创造力，善于解决复杂问题，提供创新想法', 'Creative, imaginative, free-thinking. Generates ideas and solves difficult problems.', '聪明、好奇、独立思考、非传统', 'Creative, imaginative, unorthodox', '提供创新解决方案，解决复杂技术问题', 'Generates ideas, solves difficult problems', '忽视细节、不善于沟通、过于专注自己的想法', 'Might ignore incidentals, too preoccupied to communicate effectively'),
('Resource_Investigator', '资源调查者', 'Resource Investigator', '善于发现和探索机会，外向且充满好奇心', 'Outgoing, enthusiastic. Explores opportunities and develops contacts.', '外向、热情、好奇、沟通能力强', 'Extrovert, enthusiastic, communicative', '拓展人脉、获取资源、探索新机会', 'Explores opportunities, develops contacts', '容易失去兴趣、缺乏深度跟进', 'Might be over-optimistic, can lose interest once the initial enthusiasm has passed'),
('Coordinator', '协调者', 'Coordinator', '成熟的领导者，能引导团队向目标前进', 'Mature, confident, identifies talent. Clarifies goals. Delegates effectively.', '自信、有威望、善于识别他人优势', 'Mature, confident, good chairperson', '明确目标、分配任务、促进团队合作', 'Clarifies goals, promotes decision-making, delegates well', '可能操控他人、缺乏激情', 'Can be seen as manipulative, might offload their own share of the work'),
('Shaper', '推进者', 'Shaper', '充满活力和挑战精神，推动团队克服困难', 'Challenging, dynamic, thrives on pressure. Has the drive and courage to overcome obstacles.', '有干劲、竞争性强、意志坚定', 'Challenging, dynamic, thrives on pressure', '激发动力、推动进展、挑战低效', 'Shapes the way team effort is applied, directs attention generally to the setting of objectives and priorities', '易冲动、可能伤害他人感受', 'Can be seen as aggressive, might offend people''s feelings'),
('Monitor_Evaluator', '监督者', 'Monitor Evaluator', '冷静分析和判断，权衡利弊做出正确决策', 'Sober, strategic and discerning. Sees all options and judges accurately.', '冷静、有判断力、谨慎、逻辑性强', 'Sober, strategic, discerning', '评估方案、识别风险、做出明智决策', 'Judges accurately, weighs up the team''s options in a dispassionate way', '缺乏激励他人能力、可能过于批判', 'Lacks drive and ability to inspire others, can be overly critical'),
('Teamworker', '团队工作者', 'Teamworker', '支持团队，温和、敏感且灵活', 'Co-operative, perceptive and diplomatic. Listens and averts friction.', '合作、适应性强、温和、有感知力', 'Co-operative, mild, perceptive, diplomatic', '维护团队和谐、缓解冲突、支持他人', 'Listens, builds, averts friction', '在危机中犹豫不决、难以抉择', 'Indecisive in crunch situations, can be easily influenced'),
('Implementer', '执行者', 'Implementer', '将想法转化为实际行动，纪律性强且高效', 'Practical, reliable, efficient. Turns ideas into actions and organises work that needs to be done.', '纪律性、可靠、高效、保守', 'Disciplined, reliable, conservative, efficient', '组织工作、实施计划、确保质量', 'Turns ideas into practical actions', '缺乏灵活性、可能阻碍变革', 'Somewhat inflexible, slow to respond to new possibilities'),
('Completer_Finisher', '完成者', 'Completer Finisher', '注重细节，确保任务按时高质量完成', 'Painstaking, conscientious, anxious. Searches out errors. Polishes and perfects.', '注重细节、焦虑、追求完美、有责任感', 'Painstaking, conscientious, anxious', '发现错误、确保质量、按时完成任务', 'Searches out errors and omissions, delivers on time', '担心过多、可能悲观、完美主义', 'Inclined to worry unduly, reluctant to delegate'),
('Specialist', '专家', 'Specialist', '提供专业知识和技能，专注于特定领域', 'Single-minded, self-starting, dedicated. Provides knowledge and skills in rare supply.', '专注、自我驱动、追求专业技能', 'Single-minded, self-starting, dedicated', '提供专业知识、维护技术标准', 'Provides knowledge and skills in rare supply', '视野狭窄、难以参与其他领域工作', 'Contributes only on a narrow front, dwells on technicalities');

-- 插入职业建议数据
INSERT INTO career_suggestions (mbti_type, careers_zh, careers_en) VALUES
('INTJ', '["科学家","工程师","战略顾问","研究员","系统分析师","软件工程师"]', '["Scientist","Engineer","Strategic Consultant","Researcher","Systems Analyst","Software Engineer"]'),
('INTP', '["研究员","科学家","哲学家","软件工程师","大学教授","技术专家"]', '["Researcher","Scientist","Philosopher","Software Developer","University Professor","Technical Specialist"]'),
('ENTJ', '["企业高管","项目经理","律师","企业家","管理顾问"]', '["Executive","Project Manager","Lawyer","Entrepreneur","Management Consultant"]'),
('ENTP', '["企业家","市场营销","公关专家","创新顾问","咨询师"]', '["Entrepreneur","Marketing Specialist","Public Relations","Innovation Consultant","Consultant"]'),
('INFJ', '["心理咨询师","教师","作家","人力资源","社会工作者"]', '["Psychologist","Teacher","Writer","Human Resources","Social Worker"]'),
('INFP', '["作家","心理咨询师","艺术家","社会工作者","培训师"]', '["Writer","Counselor","Artist","Social Worker","Trainer"]'),
('ENFJ', '["教师","培训师","人力资源经理","公关经理","心理咨询师"]', '["Teacher","Trainer","HR Manager","Public Relations Manager","Counselor"]'),
('ENFP', '["记者","演员","创意总监","市场营销","培训师"]', '["Journalist","Actor","Creative Director","Marketing","Trainer"]'),
('ISTJ', '["会计师","审计师","行政主管","质量控制","运营经理"]', '["Accountant","Auditor","Administrative Manager","Quality Control","Operations Manager"]'),
('ISFJ', '["护士","教师","人力资源","客户服务经理","社会工作者"]', '["Nurse","Teacher","Human Resources","Customer Service Manager","Social Worker"]'),
('ESTJ', '["管理者","军官","项目经理","运营经理","行政主管"]', '["Manager","Military Officer","Project Manager","Operations Manager","Administrator"]'),
('ESFJ', '["人力资源","护士","教师","客户服务","活动策划"]', '["Human Resources","Nurse","Teacher","Customer Service","Event Planner"]'),
('ISTP', '["技术专家","工程师","外科医生","机械师","程序员"]', '["Technical Specialist","Engineer","Surgeon","Mechanic","Programmer"]'),
('ISFP', '["设计师","艺术家","音乐家","兽医","心理咨询师"]', '["Designer","Artist","Musician","Veterinarian","Counselor"]'),
('ESTP', '["销售代表","警察","运动员","企业家","急救医生"]', '["Sales Representative","Police Officer","Athlete","Entrepreneur","Emergency Doctor"]'),
('ESFP', '["演员","活动策划","销售代表","教师","社会工作者"]', '["Actor","Event Planner","Sales Representative","Teacher","Social Worker"]');

